#pragma once

#define ENV_BASE_DIRECTORY         ".cmap"
#define ENV_CONFIGURATION_FILENAME ENV_BASE_DIRECTORY "config"
#define ENV_STORAGE_DIRECTORY      ENV_BASE_DIRECTORY "\\storage"
#define ENV_FILES_FILENAME         ENV_BASE_DIRECTORY "\\files"
#define ENV_COMMITMAP_FILENAME     ENV_BASE_DIRECTORY "\\map"

#define ENV_COMMIT_HASH_LENGTH       32
#define ENV_COMMIT_HASH_RANDOM_CHARS "fdaceb0123456789"